site_name: DJI Drone Metadata Embedder
site_description: Embed DJI drone telemetry in video files and convert tracks
repo_url: https://github.com/example/dji-drone-metadata-embedder
site_dir: site
nav:
  - Home: index.md
  - Development Roadmap: development_roadmap.md
  - How-to Guides:
      - Embed GPS: how-to/embed-gps.md
      - Strip serial number: how-to/strip-serial-number.md
      - Generate GPX: how-to/generate-gpx.md
      - Windows Quick Setup: how-to/windows-bundle.md
  - Reference:
      - API Reference: api.md
      - Metadata Checker: METADATA_CHECKER.md
      - SRT Formats: SRT_FORMATS.md
      - Release Process: RELEASE.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
