import json
import re
from datetime import datetime

from dji_metadata_embedder.geo.map_html import mixed_to_geojson, mixed_to_html
from dji_metadata_embedder.geo.photomap import PhotoPoint
from dji_metadata_embedder.geo.track import Track, TrackPoint

POINTS = [
    PhotoPoint(
        lat=60.17,
        lon=24.95,
        alt=95.3,
        name="church.jpg",
        timestamp="2026-06-15 12:30:45",
        model="FC8482",
        thumbnail_b64="/9j/THUMB1",
    ),
    PhotoPoint(
        lat=60.18, lon=24.96, alt=None, name="sphere.jpg", is_pano=True, pano_yaw=45.0
    ),
]

TRACKS = [
    Track(
        name="DJI_0001",
        points=[
            TrackPoint(
                lat=60.19,
                lon=24.97,
                alt=5.0,
                timestamp="00:00:00,000",
                utc=datetime(2026, 6, 15, 12, 0, 0),
            ),
            TrackPoint(
                lat=60.191,
                lon=24.971,
                alt=6.5,
                timestamp="00:00:01,000",
                utc=datetime(2026, 6, 15, 12, 1, 0),
            ),
        ],
    ),
]


def test_mixed_geojson_tags_every_feature_by_type():
    data = mixed_to_geojson(POINTS, TRACKS)
    types = [f["properties"]["type"] for f in data["features"]]
    assert types == ["photo", "pano", "track"]
    assert data["type"] == "FeatureCollection"


def test_mixed_geojson_keeps_photo_thumbnails_and_track_playback():
    data = mixed_to_geojson(POINTS, TRACKS)
    photo, _pano, track = data["features"]
    assert photo["properties"]["thumb"] == "/9j/THUMB1"
    assert track["geometry"]["type"] == "LineString"
    assert track["properties"]["times_s"] == [0.0, 60.0]


def test_mixed_geojson_records_redaction_mode():
    assert mixed_to_geojson(POINTS, TRACKS)["redacted"] == "none"
    assert mixed_to_geojson(POINTS, TRACKS, redact="fuzz")["redacted"] == "fuzz"


def test_mixed_geojson_links_are_opt_in():
    no_links = mixed_to_geojson(POINTS, TRACKS)
    assert all("link" not in f["properties"] for f in no_links["features"])
    linked = mixed_to_geojson(POINTS, TRACKS, link_base="")
    assert linked["features"][0]["properties"]["link"] == "church.jpg"


def test_mixed_geojson_single_type_folders():
    assert [
        f["properties"]["type"] for f in mixed_to_geojson(POINTS, [])["features"]
    ] == ["photo", "pano"]
    assert [
        f["properties"]["type"] for f in mixed_to_geojson([], TRACKS)["features"]
    ] == ["track"]


_DATA_RE = re.compile(
    r'<script type="application/json" id="(?:map|flight)-data">(.*?)</script>',
    re.DOTALL,
)


def _embedded(html: str) -> dict:
    match = _DATA_RE.search(html)
    assert match, "map-data script block not found"
    return json.loads(match.group(1))


def test_html_embeds_all_types_in_one_block():
    html = mixed_to_html(POINTS, TRACKS, title="Mixed folder")
    types = [f["properties"]["type"] for f in _embedded(html)["features"]]
    assert types == ["photo", "pano", "track"]
    assert "Mixed folder" in html


def test_html_is_pinned_and_stamped():
    html = mixed_to_html(POINTS, TRACKS, title="t")
    assert html.lstrip().startswith("<!DOCTYPE html>")
    assert "Generated by DJI Metadata Embedder" in html
    assert "leaflet@1.9.4" in html
    assert "leaflet.markercluster@1.5.3" in html
    # leaflet css+js, cluster js + 2 css — every remote asset carries SRI.
    assert html.count('integrity="sha256-') == 5


def test_html_carries_both_apps():
    html = mixed_to_html(POINTS, TRACKS, title="t")
    for marker in (
        "buildPopup",
        "photoCluster",  # photo side
        "popupHtml",
        "pb-play",
        "PALETTE",  # flight side + playback
        "360° panoramas",
    ):  # merged layer control
        assert marker in html


def test_html_pano_viewer_is_link_gated():
    plain = mixed_to_html(POINTS, TRACKS, title="t")
    assert "pannellum" not in plain
    linked = mixed_to_html(POINTS, TRACKS, title="t", link_base="")
    assert "pannellum@2.5.6" in linked
    assert linked.count('integrity="sha256-') == 7


def test_html_escapes_script_close_in_data():
    evil = [
        Track(
            name="x</script>y",
            points=[TrackPoint(lat=1.0, lon=2.0, alt=3.0, timestamp="00:00:00,000")],
        )
    ]
    html = mixed_to_html([], evil, title="t")
    data_block = _DATA_RE.search(html).group(1)
    assert "</script>" not in data_block.lower()
    assert json.loads(data_block)["features"][0]["properties"]["name"] == "x</script>y"


def test_html_renders_single_type_folders():
    assert "photoCluster" in mixed_to_html(POINTS, [], title="t")
    assert "pb-play" in mixed_to_html([], TRACKS, title="t")


def test_html_collapses_the_layer_control_past_ten_rows():
    # #515 field check: 24 flights = a 529 px legend on a 768 px viewport.
    # The threshold is a runtime count (photo/pano rows + one per flight);
    # the browser test exercises both sides of it.
    html = mixed_to_html(POINTS, TRACKS, title="t")
    assert "const LAYER_CONTROL_EXPANDED_MAX = 10;" in html
    assert "collapsed: overlayCount > LAYER_CONTROL_EXPANDED_MAX" in html
    assert "{ collapsed: false }" not in html


def test_html_gates_the_hover_toggle_on_photo_or_pano_pins():
    # #515: a tracks-only folder has nothing to preview, so the toggle
    # must not be emitted; allMarkers holds both photo and pano markers.
    html = mixed_to_html(POINTS, TRACKS, title="t")
    gate = html.index("if (allMarkers.length) {")
    assert gate < html.index('id="hover-toggle"')
    assert gate > html.index("L.control.layers(null, allOverlays")


def test_html_substitutions_are_complete():
    # A leftover placeholder is a JS SyntaxError that kills the whole page
    # while every substring assertion above stays green.
    for html in (
        mixed_to_html(POINTS, TRACKS, title="t"),
        mixed_to_html(POINTS, TRACKS, title="t", link_base=""),
        mixed_to_html(POINTS, [], title="t"),
        mixed_to_html([], TRACKS, title="t"),
    ):
        assert not re.search(r"__[A-Z_]+__", html)
        assert html.count("const esc =") == 1


def test_write_mixed_html(tmp_path):
    from dji_metadata_embedder.geo.map_html import write_mixed_html

    out = write_mixed_html(POINTS, TRACKS, tmp_path / "map.html", "t")
    assert out.read_text(encoding="utf-8").lstrip().startswith("<!DOCTYPE html>")


def test_popup_builder_is_a_standalone_block():
    from dji_metadata_embedder.geo.photomap_js import PHOTO_LAYER_JS, PHOTO_POPUP_JS

    # The 3D page (#514) reuses the popup without Leaflet: the block must
    # define both helpers and mention no Leaflet API.
    assert "function imgDims(" in PHOTO_POPUP_JS
    assert "function buildPopup(" in PHOTO_POPUP_JS
    assert "L." not in PHOTO_POPUP_JS
    # ...and the 2D layer code still carries it exactly once.
    assert PHOTO_LAYER_JS.count("function buildPopup(") == 1
    assert PHOTO_POPUP_JS in PHOTO_LAYER_JS


def test_3d_html_embeds_all_types_and_the_photo_layer():
    from dji_metadata_embedder.geo.map_html import mixed_to_3d_html

    html = mixed_to_3d_html(POINTS, TRACKS, title="t")
    fc = _embedded(html)
    assert sorted({f["properties"]["type"] for f in fc["features"]}) == [
        "pano",
        "photo",
        "track",
    ]
    assert "maplibre-gl@5." in html and 'integrity="sha256-' in html
    assert "photo-clusters" in html and "function buildPopup(" in html
    assert "const photoHooks = {" in html
    assert not re.search(r"__[A-Z_0-9]+__", html)
    assert html.count("const esc =") == 1
    assert "dji-embed" in html  # provenance stamp


def test_3d_html_pano_viewer_is_link_gated():
    from dji_metadata_embedder.geo.map_html import mixed_to_3d_html

    pano = [PhotoPoint(lat=1.0, lon=2.0, alt=3.0, name="p.jpg", is_pano=True)]
    assert "pannellum" not in mixed_to_3d_html(pano, [], title="t")
    linked = mixed_to_3d_html(pano, [], title="t", link_base="")
    assert "pannellum" in linked and 'id="pano-overlay"' in linked
    assert "function openPano(" in linked


def test_3d_html_renders_single_type_folders():
    from dji_metadata_embedder.geo.map_html import mixed_to_3d_html

    for html in (
        mixed_to_3d_html(POINTS, [], title="t"),
        mixed_to_3d_html([], TRACKS, title="t"),
    ):
        assert "<!DOCTYPE html>" in html
        assert not re.search(r"__[A-Z_0-9]+__", html)


def test_write_mixed_3d_html(tmp_path):
    from dji_metadata_embedder.geo.map_html import write_mixed_3d_html

    out = write_mixed_3d_html(POINTS, TRACKS, tmp_path / "map-3d.html", "t")
    assert out.read_text(encoding="utf-8").lstrip().startswith("<!DOCTYPE html>")
