import json
import re
from datetime import datetime

from dji_metadata_embedder.geo.map_html import mixed_to_geojson, mixed_to_html
from dji_metadata_embedder.geo.photomap import PhotoPoint
from dji_metadata_embedder.geo.track import Track, TrackPoint

POINTS = [
    PhotoPoint(lat=60.17, lon=24.95, alt=95.3, name="church.jpg",
               timestamp="2026-06-15 12:30:45", model="FC8482",
               thumbnail_b64="/9j/THUMB1"),
    PhotoPoint(lat=60.18, lon=24.96, alt=None, name="sphere.jpg",
               is_pano=True, pano_yaw=45.0),
]

TRACKS = [
    Track(name="DJI_0001", points=[
        TrackPoint(lat=60.19, lon=24.97, alt=5.0, timestamp="00:00:00,000",
                   utc=datetime(2026, 6, 15, 12, 0, 0)),
        TrackPoint(lat=60.191, lon=24.971, alt=6.5, timestamp="00:00:01,000",
                   utc=datetime(2026, 6, 15, 12, 1, 0)),
    ]),
]


def test_mixed_geojson_tags_every_feature_by_type():
    data = mixed_to_geojson(POINTS, TRACKS)
    types = [f["properties"]["type"] for f in data["features"]]
    assert types == ["photo", "pano", "track"]
    assert data["type"] == "FeatureCollection"


def test_mixed_geojson_keeps_photo_thumbnails_and_track_playback():
    data = mixed_to_geojson(POINTS, TRACKS)
    photo, pano, track = data["features"]
    assert photo["properties"]["thumb"] == "/9j/THUMB1"
    assert track["geometry"]["type"] == "LineString"
    assert track["properties"]["times_s"] == [0.0, 60.0]


def test_mixed_geojson_records_redaction_mode():
    assert mixed_to_geojson(POINTS, TRACKS)["redacted"] == "none"
    assert mixed_to_geojson(POINTS, TRACKS, redact="fuzz")["redacted"] == "fuzz"


def test_mixed_geojson_links_are_opt_in():
    no_links = mixed_to_geojson(POINTS, TRACKS)
    assert all("link" not in f["properties"] for f in no_links["features"])
    linked = mixed_to_geojson(POINTS, TRACKS, link_base="")
    assert linked["features"][0]["properties"]["link"] == "church.jpg"


def test_mixed_geojson_single_type_folders():
    assert [f["properties"]["type"]
            for f in mixed_to_geojson(POINTS, [])["features"]] == ["photo", "pano"]
    assert [f["properties"]["type"]
            for f in mixed_to_geojson([], TRACKS)["features"]] == ["track"]


_DATA_RE = re.compile(
    r'<script type="application/json" id="map-data">(.*?)</script>',
    re.DOTALL,
)


def _embedded(html: str) -> dict:
    match = _DATA_RE.search(html)
    assert match, "map-data script block not found"
    return json.loads(match.group(1))


def test_html_embeds_all_types_in_one_block():
    html = mixed_to_html(POINTS, TRACKS, title="Mixed folder")
    types = [f["properties"]["type"] for f in _embedded(html)["features"]]
    assert types == ["photo", "pano", "track"]
    assert "Mixed folder" in html


def test_html_is_pinned_and_stamped():
    html = mixed_to_html(POINTS, TRACKS, title="t")
    assert html.lstrip().startswith("<!DOCTYPE html>")
    assert "Generated by DJI Metadata Embedder" in html
    assert "leaflet@1.9.4" in html
    assert "leaflet.markercluster@1.5.3" in html
    # leaflet css+js, cluster js + 2 css — every remote asset carries SRI.
    assert html.count('integrity="sha256-') == 5


def test_html_carries_both_apps():
    html = mixed_to_html(POINTS, TRACKS, title="t")
    for marker in ("buildPopup", "photoCluster",       # photo side
                   "popupHtml", "pb-play", "PALETTE",  # flight side + playback
                   "360° panoramas"):                  # merged layer control
        assert marker in html


def test_html_pano_viewer_is_link_gated():
    plain = mixed_to_html(POINTS, TRACKS, title="t")
    assert "pannellum" not in plain
    linked = mixed_to_html(POINTS, TRACKS, title="t", link_base="")
    assert "pannellum@2.5.6" in linked
    assert linked.count('integrity="sha256-') == 7


def test_html_escapes_script_close_in_data():
    evil = [Track(name="x</script>y", points=[
        TrackPoint(lat=1.0, lon=2.0, alt=3.0, timestamp="00:00:00,000")])]
    html = mixed_to_html([], evil, title="t")
    data_block = _DATA_RE.search(html).group(1)
    assert "</script>" not in data_block.lower()
    assert json.loads(data_block)["features"][0]["properties"]["name"] == "x</script>y"


def test_html_renders_single_type_folders():
    assert "photoCluster" in mixed_to_html(POINTS, [], title="t")
    assert "pb-play" in mixed_to_html([], TRACKS, title="t")


def test_write_mixed_html(tmp_path):
    from dji_metadata_embedder.geo.map_html import write_mixed_html
    out = write_mixed_html(POINTS, TRACKS, tmp_path / "map.html", "t")
    assert out.read_text(encoding="utf-8").lstrip().startswith("<!DOCTYPE html>")
