"""Provenance stamp shared by every HTML writer.

Two honest markers, single-sourced here so wording and version can never
drift between pages: a generator comment at the top of every emitted
document (view-source only), and a small credit link for the pages that
already have a map attribution control — the corner strip where web-map
generators conventionally sign their output. Plain metadata, no tracking,
no hidden markers.
"""

from __future__ import annotations

from .. import __version__

REPO_URL = "https://github.com/CallMarcus/dji-drone-metadata-embedder"


def generator_comment() -> str:
    """The one-line generator comment, versioned from the package."""
    return (
        f"<!-- Generated by DJI Metadata Embedder v{__version__} (MIT) "
        f"— {REPO_URL} -->"
    )


def stamp(html: str) -> str:
    """Insert the generator comment directly after the doctype."""
    return html.replace(
        "<!DOCTYPE html>", "<!DOCTYPE html>\n" + generator_comment(), 1
    )


def attribution_credit() -> str:
    """The credit link for map attribution controls (trusted HTML)."""
    return f'<a href="{REPO_URL}">dji-embed</a>'
