PackageIdentifier: CallMarcus.DJI-Embed
PackageVersion: 1.0.4
PackageLocale: en-US
PackageName: DJI Drone Metadata Embedder
Publisher: CallMarcus
ShortDescription: Embed DJI drone SRT telemetry as metadata in MP4 files.
ManifestType: locale
ManifestVersion: 1.5.0
