PackageIdentifier: CallMarcus.DJI-Embed
PackageVersion: 1.0.4
PackageName: DJI Drone Metadata Embedder
Publisher: CallMarcus
Moniker: dji-embed
License: MIT
LicenseUrl: https://github.com/CallMarcus/dji-drone-metadata-embedder/blob/master/LICENSE
ShortDescription: Embed DJI drone SRT telemetry as metadata in MP4 files.
DefaultLocale: en-US
ManifestType: manifest
ManifestVersion: 1.5.0
