PackageIdentifier: CallMarcus.DJI-Embed.ExifTool
PackageVersion: 0.0.0
PackageName: DJI Embedder ExifTool Bundle
Publisher: CallMarcus
License: MIT
LicenseUrl: https://github.com/CallMarcus/dji-drone-metadata-embedder/blob/master/LICENSE
ShortDescription: Reference manifest for ExifTool.
PackageDependencies:
  - PackageIdentifier: PhilHarvey.ExifTool
ManifestType: installer
ManifestVersion: 1.5.0
