PackageIdentifier: CallMarcus.DJI-Embed.FFmpeg
PackageVersion: 0.0.0
PackageName: DJI Embedder FFmpeg Bundle
Publisher: CallMarcus
License: MIT
LicenseUrl: https://github.com/CallMarcus/dji-drone-metadata-embedder/blob/master/LICENSE
ShortDescription: Reference manifest for FFmpeg.
PackageDependencies:
  - PackageIdentifier: Gyan.FFmpeg
ManifestType: installer
ManifestVersion: 1.5.0
