PackageIdentifier: CallMarcus.DJI-Embed.Python
PackageVersion: 0.0.0
PackageName: DJI Embedder Python Runtime
Publisher: CallMarcus
License: MIT
LicenseUrl: https://github.com/CallMarcus/dji-drone-metadata-embedder/blob/master/LICENSE
ShortDescription: Reference manifest for Python runtime.
PackageDependencies:
  - PackageIdentifier: Python.Python.3
    MinimumVersion: 3.10
ManifestType: installer
ManifestVersion: 1.5.0
