PackageIdentifier: CallMarcus.DJIMetadataEmbedder
PackageVersion: 1.0.6
PackageLocale: en-US
Publisher: CallMarcus
PublisherUrl: https://github.com/CallMarcus
PublisherSupportUrl: https://github.com/CallMarcus/dji-drone-metadata-embedder/issues
Author: CallMarcus
PackageName: DJI Metadata Embedder
PackageUrl: https://github.com/CallMarcus/dji-drone-metadata-embedder
License: MIT
LicenseUrl: https://github.com/CallMarcus/dji-drone-metadata-embedder/blob/main/LICENSE
Copyright: Copyright (c) 2024 CallMarcus
ShortDescription: Embed telemetry from DJI drone SRT files into MP4 videos
Description: |
  DJI Metadata Embedder is a comprehensive tool for processing DJI drone footage.
  
  Features:
  - Embed SRT telemetry data into MP4 videos as subtitle tracks
  - Add GPS metadata to videos for geolocation
  - Support for multiple DJI drone models (Mini 3/4 Pro, Avata 2, Air 3)
  - Export telemetry to GPX for mapping software
  - Export telemetry to CSV for analysis
  - Process DAT flight logs
  - Batch processing capabilities
  - Rich progress reporting
Moniker: dji-embed
Tags:
  - dji
  - drone
  - metadata
  - video
  - telemetry
  - gps
  - exiftool
  - ffmpeg
ReleaseNotes: |
  - Fixed package structure and imports
  - Enhanced error handling
  - Improved progress reporting
  - Updated documentation
ReleaseNotesUrl: https://github.com/CallMarcus/dji-drone-metadata-embedder/releases/tag/v1.0.6
ManifestType: defaultLocale
ManifestVersion: 1.4.0
