PackageIdentifier: CallMarcus.DJIMetadataEmbedder
PackageVersion: 1.0.6
MinimumOSVersion: 10.0.0.0
Scope: user
InstallModes:
  - interactive
  - silent
UpgradeBehavior: install
Commands:
  - dji-embed
Installers:
  - Architecture: x64
    InstallerType: portable
    InstallerUrl: https://github.com/CallMarcus/dji-drone-metadata-embedder/releases/download/v1.0.6/dji-embed.exe
    InstallerSha256: PLACEHOLDER_SHA256
ManifestType: installer
ManifestVersion: 1.4.0
