PackageIdentifier: CallMarcus.DJIMetadataEmbedder
PackageVersion: 1.0.6
MinimumOSVersion: 10.0.0.0
Scope: user
InstallModes:
  - interactive
  - silent
UpgradeBehavior: install
Commands:
  - dji-embed
Installers:
  - Architecture: x64
    InstallerType: portable
    InstallerUrl: https://github.com/CallMarcus/dji-drone-metadata-embedder/releases/download/v1.0.6/dji-embed.exe
    InstallerSha256: D2B4E91A6C776AD710EB3D9ED8B6F4CC006FF7E2DBC2A45A8054BBBD804E90D3
ManifestType: installer
ManifestVersion: 1.4.0
