name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install ruff mypy pytest build
      - name: Ruff
        run: ruff check .
      - name: Mypy
        run: mypy
      - name: Pytest
        run: pytest
      - name: Build package
        run: python -m build

  windows-bootstrap-smoke-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bootstrap and verify
        shell: powershell
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          .\tools\bootstrap.ps1 -Silent -NoLaunch
          dji-embed --version
