name: Publish winget package

on:
  push:
    branches: [winget-update]

jobs:
  publish-winget:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install wingetcreate
        run: pip install wingetcreate
      - name: Submit package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: wingetcreate update -i .github/winget/installer.yaml --submit --token $env:GITHUB_TOKEN
