name: Publish winget package

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish-winget:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          Invoke-WebRequest -Uri https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
      - name: Build executable
        run: pyinstaller --onefile -n dji-embed dji_metadata_embedder/embedder.py
      - name: Publish via wingetcreate
        env:
          WINGET_TOKEN: ${{ secrets.WINGET_GITHUB_TOKEN }}
        run: |
          $version = (Select-String -Path pyproject.toml -Pattern '^version').Line.Split('=')[1].Trim().Trim('"')
          $tag = "v$version"
          $url = "https://github.com/${{ github.repository }}/releases/download/$tag/dji-embed.exe"
          .\wingetcreate.exe update CallMarcus.DJI-Embed -v $version -u $url -t $env:WINGET_TOKEN --submit
          $pyUrl = "https://github.com/${{ github.repository }}/releases/download/$tag/python.zip"
          .\wingetcreate.exe update CallMarcus.DJI-Embed.Python -v $version -u $pyUrl -t $env:WINGET_TOKEN --submit
          $ffUrl = "https://github.com/${{ github.repository }}/releases/download/$tag/ffmpeg.zip"
          .\wingetcreate.exe update CallMarcus.DJI-Embed.FFmpeg -v $version -u $ffUrl -t $env:WINGET_TOKEN --submit
          $exUrl = "https://github.com/${{ github.repository }}/releases/download/$tag/exiftool.zip"
          .\wingetcreate.exe update CallMarcus.DJI-Embed.ExifTool -v $version -u $exUrl -t $env:WINGET_TOKEN --submit
