---
name: Publish winget package

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - winget-update
  workflow_dispatch:

jobs:
  publish-winget:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install wingetcreate (submission tool)
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://aka.ms/wingetcreate/latest `
            -OutFile wingetcreate.exe

        find-next-steps-for-winget-push-and-pr
      - name: Install winget CLI
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://aka.ms/getwinget `
            -OutFile winget.msixbundle
          Add-AppxPackage winget.msixbundle


      - name: Validate manifest
        shell: powershell
        run: |
          Write-Host 'Validating manifest…'
          winget validate .github/winget-manifests/CallMarcus.DJIMetadataEmbedder.yaml

      - name: Submit package
        shell: powershell
        env:
          WINGET_PAT: ${{ secrets.WINGET_PAT }}
        run: |
          Write-Host 'Submitting package…'
          .\wingetcreate.exe submit `
            .github/winget-manifests/CallMarcus.DJIMetadataEmbedder.yaml `
            --token $env:WINGET_PAT
