---
name: Publish winget package

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - winget-update
  workflow_dispatch:

jobs:
  publish-winget:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install wingetcreate (submission tool)
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://aka.ms/wingetcreate/latest `
            -OutFile wingetcreate.exe

      - name: Ensure winget CLI
        shell: pwsh
        run: |
          if (-not (Get-Command winget -ErrorAction SilentlyContinue)) {
            Invoke-WebRequest -Uri https://aka.ms/getwinget `
              -OutFile winget.msixbundle
            Add-AppxPackage winget.msixbundle
          }

      - name: Validate manifest
        shell: pwsh
        run: |
          $cmd = Get-Command winget.exe -ErrorAction SilentlyContinue
          $winget = $cmd.Source
          if (-not $winget) {
            $pkg = Get-AppxPackage Microsoft.DesktopAppInstaller
            $winget = Join-Path $pkg.InstallLocation 'winget.exe'
          }
          & $winget validate `
            .github/winget-manifests/CallMarcus.DJIMetadataEmbedder.yaml

      - name: Submit package
        shell: pwsh
        env:
          WINGET_PAT: ${{ secrets.WINGET_PAT }}
        run: |
          .\wingetcreate.exe submit `
            .github/winget-manifests/CallMarcus.DJIMetadataEmbedder.yaml `
            --token $env:WINGET_PAT
