name: Publish winget package

"on":
  push:
    branches:
      - winget-update
  workflow_dispatch:

jobs:
  publish-winget:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install wingetcreate
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://aka.ms/wingetcreate/latest `
            -OutFile wingetcreate.exe

      - name: Submit package
        shell: pwsh
        env:
          WINGET_PAT: ${{ secrets.WINGET_PAT }}
        run: |
          .\wingetcreate.exe submit .github/winget/installer.yaml `
            --token $env:WINGET_PAT
