---
name: Winget Submission

"on":
  push:
    branches:
      - winget-update
  workflow_dispatch:

jobs:
  build-windows-exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pyinstaller
      - name: Build executable
        run: |
          python tools/build_windows_exe.py
      - name: Calculate SHA256
        id: sha256
        run: |
          $hash = Get-FileHash -Path "dist\dji-embed.exe" -Algorithm SHA256
          echo "hash=$($hash.Hash)" >> $env:GITHUB_OUTPUT
          echo "SHA256: $($hash.Hash)"
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/dji-embed.exe
      - name: Create Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/dji-embed.exe
        env:
          GITHUB_TOKEN: ${{ secrets.WINGET_PAT }}  # Use WINGET_PAT for release creation

  publish-winget:
    runs-on: windows-latest
    needs: build-windows-exe
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install wingetcreate
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://aka.ms/wingetcreate/latest `
            -OutFile wingetcreate.exe
      - name: Validate manifest
        shell: pwsh
        run: |
          .\wingetcreate.exe validate .github/winget/CallMarcus.DJI-Embed.yaml
      - name: Submit package
        shell: pwsh
        env:
          WINGET_PAT: ${{ secrets.WINGET_PAT }}
        run: |
          .\wingetcreate.exe submit .github/winget/CallMarcus.DJI-Embed.yaml `
            --token $env:WINGET_PAT
